global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'example-project'
    static_configs:
      - targets: ['time-slots:8080', 'personal-data:8080', 'mailing-service:8080']